### ISSUE TITLE
Upload inserted images

### ISSUE THREAD

**Issue by E-Mans-Application** [dankito/RichTextEditor#5]
Hello,

That's me again.
I'm trying to implement an automatic image upload when they are inserted into the editor.
I use:

```
@Override
protected void onCreate(final Bundle savedInstanceState) {
[...]
    editorToolbar.addCommandInvokedListener(this::editorCommandInvoked);
[...]
}
```
```
private Unit editorCommandInvoked(final ToolbarCommand command){

        switch(command.getCommand()){

            case INSERTIMAGE:
                //TODO UPLOAD IMAGE
                break;

        }

        return Unit.INSTANCE;

}
```

I don't know how to:
- get the image URL;
- cancel the insertion if upload fails;
- update the image URL with the one generated by the server (if I can get
the local URL, it should be easy)

Is it currently possible?

**Comment by dankito** [comment]
The CommandInvoked listener gets fired if a toolbar button is pressed.

It's simply there so that the toolbar commands know that they now have to do their work.

It does not say anything if the HTML has changed or not.

Actually there's currently no mechanism telling you 'an image has been inserted'.

It would take me some effort to implement it, but anyway for your synchronizing issue I actually think it's the wrong approach.
Imagine the following cases:
- The user adds an image and then immediately removes it again -> you would have uploaded an image that's not in the document anymore.
- The user doesn't save the document at all -> same result.
- The user is in an area with a bad internet connection so that the upload fails -> he/she would be really angry that he/she cannot add his/her local image to the document simply because the upload fails.
- Or the bandwith is very low, so the user may have to wait ages till the image is uploaded whilst the only thing he/she likes to do is continue working on his/her document.

I'd rather wait till the document gets saved and then use the mechanism posted somewhere else to determine which images have been added and which ones have been removed.

For keeping track of the images you could do the following:
- As CouchbaseLite does it: Calculate the file hash of the local image. So no matter how it is named or where it is stored, you find duplicates already uploaded.
- With this file hash you can keep track of an image: Add it to a database with state 'not uploaded yet'.
- Implement an async worker that gets images to be uploaded from database and uploads it in background. As soon as it's uploaded it's state gets changed to 'uploaded'.

So it does not matter if the user currently has internet access or not, as soon as it's back again the upload starts.

You may also can add a counter, how often that image is used.
Imagine an image is added two times in different documents -> counter is 2.
Then it gets removed from one document -> counter decreases to 1, but as it's still larger than 0 you know that you don't have to remove it from server yet.

By the way, there comes to my mind, that local images currently get added with their absolute path to document.
In order for synchronization to properly work I have to added them with relative path.

**Comment by E-Mans-Application** [comment]
You're right.

I used your suggestion at #2 (by replacing href with src, href is for links)

The upload was already in background in didn't prevent the user from continuing editing, but I now make all uploads when the user saves the document. If the uploads fails, the local url is kept, and the application will attempt a new upload on next save.

And do not worry, the server already checks whether a image is still used before deleting it.

I should still implement a hash-check to prevent the app from re-uploading images that are already uploaded.
